[general]
refresh_interval = 5

[http]
timeout = 60

[[clusters]]
alias  = "testcluster1"
endpoint = "http://localhost:9200"
username = "user"
password = "password"

[[clusters]]
alias  = "testcluster2"
endpoint = "http://testcluster2:9200"
username = "user"

[[clusters]]
alias  = "testcluster3"
endpoint = "http://testcluster3:9200"
